import type { Employee, Client, Project, Task } from "@/types";

export const MOCK_EMPLOYEES: Employee[] = [
  {
    id: "e1",
    name: "Ahmed Al-Rashidi",
    email: "ahmed@nabel.sa",
    role: "manager",
    position: "Project Manager",
    department: "Engineering",
    phone: "+966 50 123 4567",
    status: "active",
    joinedAt: "2022-03-15",
    avatar: "https://ui-avatars.com/api/?name=Ahmed+Al-Rashidi&background=5B3B8A&color=fff",
  },
  {
    id: "e2",
    name: "Sara Al-Ghamdi",
    email: "sara@nabel.sa",
    role: "employee",
    position: "Sales Engineer",
    department: "Sales",
    phone: "+966 55 234 5678",
    status: "active",
    joinedAt: "2023-01-10",
    avatar: "https://ui-avatars.com/api/?name=Sara+Al-Ghamdi&background=8E6BC4&color=fff",
  },
  {
    id: "e3",
    name: "Mohammed Al-Zahrani",
    email: "mohammed@nabel.sa",
    role: "employee",
    position: "Installation Technician",
    department: "Operations",
    phone: "+966 54 345 6789",
    status: "active",
    joinedAt: "2021-07-20",
    avatar: "https://ui-avatars.com/api/?name=Mohammed+Al-Zahrani&background=5B3B8A&color=fff",
  },
  {
    id: "e4",
    name: "Fatima Al-Otaibi",
    email: "fatima@nabel.sa",
    role: "employee",
    position: "Finance Officer",
    department: "Finance",
    phone: "+966 56 456 7890",
    status: "active",
    joinedAt: "2022-11-05",
    avatar: "https://ui-avatars.com/api/?name=Fatima+Al-Otaibi&background=8E6BC4&color=fff",
  },
  {
    id: "e5",
    name: "Khalid Al-Dosari",
    email: "khalid@nabel.sa",
    role: "admin",
    position: "General Manager",
    department: "Management",
    phone: "+966 50 567 8901",
    status: "active",
    joinedAt: "2020-01-01",
    avatar: "https://ui-avatars.com/api/?name=Khalid+Al-Dosari&background=5B3B8A&color=fff",
  },
];

export const MOCK_CLIENTS: Client[] = [
  {
    id: "c1",
    name: "Abdullah Al-Saud",
    company: "Royal Palace Project",
    email: "a.saud@royalpalace.sa",
    phone: "+966 50 111 2222",
    status: "active",
    createdAt: "2023-06-01",
    projectCount: 3,
  },
  {
    id: "c2",
    name: "Turki Al-Faisal",
    company: "Kingdom Tower LLC",
    email: "t.faisal@kingdomtower.sa",
    phone: "+966 55 333 4444",
    status: "active",
    createdAt: "2023-09-15",
    projectCount: 2,
  },
  {
    id: "c3",
    name: "Nasser Al-Qasim",
    company: "Riyadh Municipal Authority",
    email: "n.qasim@rma.gov.sa",
    phone: "+966 11 555 6666",
    status: "active",
    createdAt: "2024-01-20",
    projectCount: 5,
  },
  {
    id: "c4",
    name: "Badr Al-Mutairi",
    company: "ROSHN Real Estate",
    email: "b.mutairi@roshn.sa",
    phone: "+966 50 777 8888",
    status: "pending",
    createdAt: "2024-03-10",
    projectCount: 1,
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: "p1",
    title: "Royal Palace UPVC Windows Installation",
    description: "Full window installation for the royal palace complex — 480 UPVC units.",
    clientId: "c1",
    clientName: "Royal Palace Project",
    managerId: "e1",
    managerName: "Ahmed Al-Rashidi",
    status: "active",
    priority: "urgent",
    startDate: "2024-02-01",
    endDate: "2024-08-30",
    budget: 4500000,
    progress: 65,
    teamIds: ["e2", "e3"],
  },
  {
    id: "p2",
    title: "Kingdom Tower Glass Facades",
    description: "Floor-to-ceiling glass facade system for floors 20-50.",
    clientId: "c2",
    clientName: "Kingdom Tower LLC",
    managerId: "e1",
    managerName: "Ahmed Al-Rashidi",
    status: "active",
    priority: "high",
    startDate: "2024-03-15",
    endDate: "2024-12-15",
    budget: 8200000,
    progress: 30,
    teamIds: ["e3"],
  },
  {
    id: "p3",
    title: "Municipal Schools Window Replacement",
    description: "Replacing 1,200 windows across 15 government schools in Riyadh.",
    clientId: "c3",
    clientName: "Riyadh Municipal Authority",
    managerId: "e1",
    managerName: "Ahmed Al-Rashidi",
    status: "completed",
    priority: "medium",
    startDate: "2023-09-01",
    endDate: "2024-01-31",
    budget: 2100000,
    progress: 100,
    teamIds: ["e2", "e3"],
  },
  {
    id: "p4",
    title: "ROSHN Housing Development Phase 1",
    description: "Supply and install 3,600 window units for 300 residential villas.",
    clientId: "c4",
    clientName: "ROSHN Real Estate",
    managerId: "e1",
    managerName: "Ahmed Al-Rashidi",
    status: "pending",
    priority: "high",
    startDate: "2024-06-01",
    endDate: "2025-03-31",
    budget: 9800000,
    progress: 0,
    teamIds: [],
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: "t1",
    title: "Submit material samples for palace project",
    projectId: "p1",
    projectName: "Royal Palace UPVC Windows",
    assigneeId: "e2",
    assigneeName: "Sara Al-Ghamdi",
    status: "completed",
    priority: "urgent",
    dueDate: "2024-02-15",
    createdAt: "2024-02-01",
    tags: ["procurement", "samples"],
  },
  {
    id: "t2",
    title: "Prepare installation schedule for palace Phase 2",
    projectId: "p1",
    projectName: "Royal Palace UPVC Windows",
    assigneeId: "e1",
    assigneeName: "Ahmed Al-Rashidi",
    status: "active",
    priority: "high",
    dueDate: "2024-04-30",
    createdAt: "2024-03-01",
    tags: ["planning", "schedule"],
  },
  {
    id: "t3",
    title: "Technical site survey — Kingdom Tower floors 20-35",
    projectId: "p2",
    projectName: "Kingdom Tower Glass Facades",
    assigneeId: "e3",
    assigneeName: "Mohammed Al-Zahrani",
    status: "active",
    priority: "high",
    dueDate: "2024-04-20",
    createdAt: "2024-03-15",
    tags: ["survey", "technical"],
  },
  {
    id: "t4",
    title: "Invoice reconciliation for municipal schools project",
    projectId: "p3",
    projectName: "Municipal Schools Window Replacement",
    assigneeId: "e4",
    assigneeName: "Fatima Al-Otaibi",
    status: "active",
    priority: "medium",
    dueDate: "2024-04-10",
    createdAt: "2024-03-20",
    tags: ["finance", "invoicing"],
  },
  {
    id: "t5",
    title: "Finalize ROSHN contract and procurement plan",
    projectId: "p4",
    projectName: "ROSHN Housing Development",
    assigneeId: "e1",
    assigneeName: "Ahmed Al-Rashidi",
    status: "pending",
    priority: "urgent",
    dueDate: "2024-05-15",
    createdAt: "2024-03-25",
    tags: ["contract", "planning"],
  },
];

export const MOCK_STATS = {
  totalEmployees: MOCK_EMPLOYEES.length,
  activeProjects: MOCK_PROJECTS.filter((p) => p.status === "active").length,
  pendingTasks: MOCK_TASKS.filter((t) => t.status === "active" || t.status === "pending").length,
  totalClients: MOCK_CLIENTS.length,
  totalRevenue: 24600000,
  monthlyRevenue: 1800000,
};
